// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	Worlds        []*World     `json:"worlds"`
	Aliases       []string     `json:"aliases"`
	Alternates    []*Character `json:"alternates"`
	Parents       []*Character `json:"parents"`
	Children      []*Character `json:"children"`
	Relationships []*Character `json:"relationships"`
}

type World struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Characters []*Character `json:"characters"`
}
